export const UPDATE_LOCATIONS_COLLECTION = 'UPDATE_LOCATIONS_COLLECTION';

export const UPDATE_STUDY_REQUESTS_COLLECTION = 'UPDATE_STUDY_REQUESTS_COLLECTION';

export const UPDATE_USER = 'UPDATE_USER';